export const authConstant = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE' ,
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    SIGNOUT_REQUEST: 'SIGNOUT_REQUEST',
    SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
    SIGNOUT_FAILURE: 'SIGNOUT_FAILURE',
}

export const caseConstant = {
    PATIENT_FETCH_CASES_SUCCESS: 'PATIENT_FETCH_CASES_SUCCESS',
    PATIENT_FETCH_CASES_REQUEST: 'PATIENT_FETCH_CASES_REQUEST',
    PATIENT_FETCH_CASES_FAILURE: 'PATIENT_FETCH_CASES_FAILURE',
    DOCTOR_FETCH_CASES_SUCCESS: 'DOCTOR_FETCH_CASES_SUCCESS',
    DOCTOR_FETCH_CASES_REQUEST: 'DOCTOR_FETCH_CASES_REQUEST',
    DOCTOR_FETCH_CASES_FAILURE: 'DOCTOR_FETCH_CASES_FAILURE'
}
